-- 修改 products 表
ALTER TABLE products 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 cart_items 表
ALTER TABLE cart_items 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 users 表
ALTER TABLE users 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 stores 表
ALTER TABLE stores 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 orders 表
ALTER TABLE orders 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 order_items 表
ALTER TABLE order_items 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 修改 suppliers 表
ALTER TABLE suppliers 
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

-- 添加必要的时间戳字段
ALTER TABLE cart_items 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE products 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE orders 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE order_items 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP; 